/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Database.DatabaseConnection;

import java.io.IOException;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author PC-08
 */
public final class UserDetails extends javax.swing.JFrame {

    DatabaseConnection dbcon;

    /**
     * Creates new form User
     */
    public UserDetails() {
        initComponents();
        dbcon = new DatabaseConnection();
        dbcon.dbconnection();
        setTitle("Registration Page");
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        txtfullname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        optMale = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        tatpid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        optFemale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtblood = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtwt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmbttype = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        txttper = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtmobile = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cmbsmoke = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        txtheight = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel3.setText("Age");

        jLabel9.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel9.setText("Gender");

        txtage.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtageKeyReleased(evt);
            }
        });

        txtfullname.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txtfullname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfullnameKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel1.setText("Patient Fullname");

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel2.setText("Patient Id");

        buttonGroup1.add(optMale);
        optMale.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        optMale.setSelected(true);
        optMale.setText("Male");

        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        tatpid.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        tatpid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tatpidActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel6.setText("Address");

        buttonGroup1.add(optFemale);
        optFemale.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        optFemale.setText("Female");
        optFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optFemaleActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel5.setText("yrs");

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel8.setText("Blood Group");

        txtblood.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txtblood.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbloodKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel12.setText("Weight");

        txtwt.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txtwt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtwtKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel13.setText("Tumour Type");

        cmbttype.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        cmbttype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Malignent" }));

        jLabel14.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel14.setText("Tumour Percent");

        txttper.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txttper.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttperKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel15.setText("Email Id");

        txtemail.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel16.setText("Contact No.");

        txtmobile.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txtmobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmobileKeyReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel17.setText("Smoke / Drink");

        cmbsmoke.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        cmbsmoke.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));
        cmbsmoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsmokeActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel18.setText("Height");

        txtheight.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txtheight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtheightKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel7.setText("cm");

        jLabel10.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel10.setText("KG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(txtfullname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(tatpid, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                    .addComponent(txtmobile)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(cmbttype, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(cmbsmoke, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(txtheight, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(101, 101, 101)
                                        .addComponent(optFemale))
                                    .addComponent(txttper, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtwt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(txtblood, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(optMale)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tatpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmobile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtage)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(optFemale)
                    .addComponent(optMale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtblood))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtwt)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtheight)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttper))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbsmoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jButton1.setMnemonic('R');
        jButton1.setText("REGISTER");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jButton3.setMnemonic('R');
        jButton3.setText("RESET ALL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jButton4.setMnemonic('L');
        jButton4.setText("Login Page");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(490, 595));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String Fullname = txtfullname.getText();
            if (Fullname.length() <= 5) {
                JOptionPane.showMessageDialog(this, "Enter Proper Name", "Error", JOptionPane.ERROR_MESSAGE);
                txtfullname.grabFocus();
                return;
            }

            String Address = txtaddress.getText();
            if (Address.length() <= 5) {
                JOptionPane.showMessageDialog(this, "Enter Proper Address Details", "Error", JOptionPane.ERROR_MESSAGE);
                txtaddress.grabFocus();
                return;
            }
            
            String PID = tatpid.getText();
            if (PID.trim().length() < 5) {
                JOptionPane.showMessageDialog(this, "Patient Id is at least 5 digits");
                tatpid.grabFocus();
                return;
            }
            if (verifyPID(PID)) {
                JOptionPane.showMessageDialog(this, "Patient Id is NOT Available Enter Another Id");
                tatpid.setText("");
                tatpid.grabFocus();
                return;
            }

            String email = txtemail.getText();
            if (verifyEmail(email) || (!(isEmailValid(email)))) {
                JOptionPane.showMessageDialog(this, "Enter proper EmailId", "Error", JOptionPane.ERROR_MESSAGE);
                txtemail.grabFocus();
                return;
            }

            String mobile = txtmobile.getText();
            if (!isPhoneNumberValid(mobile)) {
                JOptionPane.showMessageDialog(this, "Enter proper Mobile No.", "Error", JOptionPane.ERROR_MESSAGE);
                txtmobile.grabFocus();
                return;
            }
            if (verifyphone(mobile)) {
                JOptionPane.showMessageDialog(this, "Mobile no is already Registered!!!", "Error", JOptionPane.ERROR_MESSAGE);
                txtmobile.grabFocus();
                return;
            }
            
            String Gender = "Male";
            if (optMale.isSelected()) {
                Gender = "Male";
            } else {
                Gender = "Female";
            }
            
            String age = txtage.getText(); 
            if (age.length() <= 0) {
                JOptionPane.showMessageDialog(this, "Enter Patient Age Properly", "Error", JOptionPane.ERROR_MESSAGE);
                txtage.grabFocus();
                return;
            }
            
            String blood = txtblood.getText(); 
            if (blood.length() <= 0) {
                JOptionPane.showMessageDialog(this, "Enter Proper Blood Group Details", "Error", JOptionPane.ERROR_MESSAGE);
                txtblood.grabFocus();
                return;
            }
            
            String weight = txtwt.getText(); 
            if (weight.length() <= 0) {
                JOptionPane.showMessageDialog(this, "Enter Proper Weight Details", "Error", JOptionPane.ERROR_MESSAGE);
                txtwt.grabFocus();
                return;
            }
            
            String height = txtheight.getText(); 
            if (height.length() <= 0) {
                JOptionPane.showMessageDialog(this, "Enter Proper height Details", "Error", JOptionPane.ERROR_MESSAGE);
                txtheight.grabFocus();
                return;
            }
            
            String ttype = cmbttype.getSelectedItem().toString();
            
            String tper = txttper.getText();  
            if (tper.length() <= 0) {
                JOptionPane.showMessageDialog(this, "Enter Proper Tumour Percentage Details", "Error", JOptionPane.ERROR_MESSAGE);
                txttper.grabFocus();
                return;
            }
            
            String smoke = cmbsmoke.getSelectedItem().toString(); 

//            String DOB = txtDOB.getText();
//            if (DOB.length() <= 0) {
//                JOptionPane.showMessageDialog(this, "Select Date Of Birth Properly", "Error", JOptionPane.ERROR_MESSAGE);
//                txtDOB.grabFocus();
//                return;
//            }
//            int age = getAgeFromDOB(txtDOB.getText());
//            if (age <= 0) {
//                txtDOB.setText("");
//                txtDOB.grabFocus();
//                JOptionPane.showMessageDialog(this, "Can't be born in the future, Please select valid date", "Error", JOptionPane.ERROR_MESSAGE);
//                return;
//            }
//            if (age < 18) {
//                txtDOB.setText("");
//                txtDOB.grabFocus();
//                JOptionPane.showMessageDialog(this, "Sorry your age is low for this registration, Register after age 18", "Error", JOptionPane.ERROR_MESSAGE);
//                return;
//            }

            String query = "INSERT INTO patient_details VALUES('" + Fullname + "','" + Address + "','" + PID + "','" + email + "','" + mobile + "', '"+age+"', '" + Gender + "', '" + blood + "', '" + weight + "' , '" + height + "', '" + ttype + "', '" + tper + "', '" + smoke + "','','','')";
            int i = dbcon.getUpdate(query);
            System.out.println(i);
            resetall();
            JOptionPane.showMessageDialog(this, "Patient Details successfully Stored", "Welcome Message", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new LoginPage().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(UserDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean verifyPID(String pid) {
        try {
            DatabaseConnection dbcon = new DatabaseConnection();
            dbcon.dbconnection();
            ResultSet rs = dbcon.getResultSet("SELECT * FROM patient_details WHERE pid ='" + pid + "'");
            if (rs.next()) {
                return true;
            }
        } catch (Exception e) {
        }
        return false;
    }

    public boolean verifyEmail(String email) {
        try {
            DatabaseConnection dbcon = new DatabaseConnection();
            dbcon.dbconnection();
            ResultSet rs = dbcon.getResultSet("SELECT * FROM patient_details WHERE email ='" + email + "'");
            if (rs.next()) {
                return true;
            }
        } catch (Exception e) {
        }
        return false;
    }

    public boolean verifyphone(String mobile) {
        try {
            DatabaseConnection dbcon = new DatabaseConnection();
            dbcon.dbconnection();
            ResultSet rs = dbcon.getResultSet("SELECT * FROM patient_details WHERE mobile ='" + mobile + "'");
            if (rs.next()) {
                return true;
            }
        } catch (Exception e) {
        }
        return false;
    }

    public static boolean isPhoneNumberValid(String phoneNumber) {
        boolean isValid = false;

        String expression = "[789]{1}[0-9]{9}";//this to validate only 8 digit and 10 digit numbers
        CharSequence inputStr = phoneNumber;
        Pattern pattern = Pattern.compile(expression);
        Matcher matcher = pattern.matcher(inputStr);
        if (matcher.matches()) {
            isValid = true;
        }
        return isValid;
    }

    public static boolean isEmailValid(String email) {
        boolean isValid = false;

        //Initialize reg ex for email.  
        String expression = "\\b[A-Za-z0-9._%+-]+@[A-Za-z.]+\\.[A-Za-z]{2,3}\\b";
        CharSequence inputStr = email;
        //Make the comparison case-insensitive.  
        Pattern pattern = Pattern.compile(expression, Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(inputStr);
        if (matcher.matches()) {
            isValid = true;
        }
        return isValid;
    }

    public static boolean isValidpancard(String pancard) {
        boolean isValid = false;

        //Initialize reg ex for PANCARD NO.
        String expression = "[A-Z]{5}[0-9]{4}[A-Z]{1}";
        CharSequence inputStr = pancard;
        //Make the comparison case-insensitive.  
        Pattern pattern = Pattern.compile(expression, Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(inputStr);
        if (matcher.matches()) {
            isValid = true;
        }
        return isValid;
    }

    public void resetall() {
        txtfullname.setText("");
        txtaddress.setText("");
        tatpid.setText("");
        txtage.setText("");
        txtemail.setText("");
        txtmobile.setText("");
        txtage.setText("");
        txtblood.setText("");
        txtwt.setText("");
        txtheight.setText("");
        cmbttype.setSelectedIndex(0);
        txttper.setText("");
        cmbsmoke.setSelectedIndex(0);
    }
    private void tatpidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tatpidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tatpidActionPerformed

    public int getAgeFromDOB(String DOB) {
        Calendar now = Calendar.getInstance();
        Calendar dob = Calendar.getInstance();
//    	      //take substrings of the dob so split out year, month and day
        int y = Integer.parseInt(DOB.substring(6, 10));
        int m = Integer.parseInt(DOB.substring(3, 5));
        int d = Integer.parseInt(DOB.substring(0, 2));
        dob.set(y, m, d);
        if (dob.after(now)) {
            System.out.println("here low date");
        }

        int year1 = now.get(Calendar.YEAR);
        int year2 = dob.get(Calendar.YEAR);
        int age = year1 - year2;
        int month1 = now.get(Calendar.MONTH);
        int month2 = dob.get(Calendar.MONTH);

        if (month2 > month1) {
            age--;
        } else if (month1 == month2) {
            int day1 = now.get(Calendar.DAY_OF_MONTH);
            int day2 = dob.get(Calendar.DAY_OF_MONTH);
            if (day2 > day1) {
                age--;
            }
        }
        System.out.println("Age is : " + age);
        return 18;
    }
    private void optFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optFemaleActionPerformed

    private void txtageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyReleased
        // TODO add your handling code here:
        JTextField tf = (JTextField) evt.getSource();
        String text = tf.getText();
        text = text.replaceAll("[^0-9]", "");
        tf.setText(text);
    }//GEN-LAST:event_txtageKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        resetall();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtfullnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfullnameKeyReleased
        // TODO add your handling code here:
        JTextField tf = (JTextField) evt.getSource();
        String text = tf.getText();
        text = text.replaceAll("[0-9]", "");
        tf.setText(text);
    }//GEN-LAST:event_txtfullnameKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtbloodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbloodKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbloodKeyReleased

    private void txtwtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtwtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtwtKeyReleased

    private void txttperKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttperKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txttperKeyReleased

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailKeyReleased

    private void txtmobileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmobileKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobileKeyReleased

    private void txtheightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtheightKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtheightKeyReleased

    private void cmbsmokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsmokeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbsmokeActionPerformed
    public static void main(String[] a) throws InterruptedException, IOException {
//        try {
//            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
//            new UserDetails().setVisible(true);
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
//        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbsmoke;
    private javax.swing.JComboBox cmbttype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JRadioButton optFemale;
    public static javax.swing.JRadioButton optMale;
    public static javax.swing.JTextField tatpid;
    public static javax.swing.JTextArea txtaddress;
    public static javax.swing.JTextField txtage;
    public static javax.swing.JTextField txtblood;
    public static javax.swing.JTextField txtemail;
    public static javax.swing.JTextField txtfullname;
    public static javax.swing.JTextField txtheight;
    public static javax.swing.JTextField txtmobile;
    public static javax.swing.JTextField txttper;
    public static javax.swing.JTextField txtwt;
    // End of variables declaration//GEN-END:variables
}
